# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0

kind: Kustomization
bases:
  - ../istio-auth
resources:
  - kubeflow-dashboard-patch.yaml
  - oidc-patch.yaml
  - envoy-filter-patch.yaml
patchesStrategicMerge:
  - mlx-ui-patch.yaml
  - mlx-ext-authz-patch.yaml
