# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlx-ui
  namespace: kubeflow
  labels:
    service: mlx-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mlx-ui
  template:
    metadata:
      name: mlx-ui
      labels:
        service: mlx-ui
    spec:
      containers:
      - name: mlx-ui
        # You can use your own webapp image below
        image: mlexchange/mlx-ui:nightly-origin-main
        imagePullPolicy: Always
        env:
        - name: REACT_APP_BRAND
          value: "Machine Learning eXchange"
        - name: REACT_APP_RUN
          value: "true"
        - name: REACT_APP_UPLOAD
          value: "true"
        - name: REACT_APP_BASE_PATH
          value: ""
        - name: REACT_APP_DISABLE_LOGIN
          value: "false"
        - name: KUBEFLOW_USERID_HEADER
          value: kubeflow-userid
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: mlx-dashboard-admin
              key: session
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /workspace/models
          name: dashboard-admin
          readOnly: true
          # When deploying MLX on OpenShift, readOnly SCC may be required for mlx-ui.
      volumes:
      - name: dashboard-admin
        secret:
          items:
          - key: admin.json
            path: admin.json
          secretName: mlx-dashboard-admin
      serviceAccountName: mlx-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mlx-ui
  namespace: kubeflow
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: mlx-ui.kubeflow.svc.cluster.local
        port:
          number: 80
    timeout: 300s
