# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0

# Since this modify the istio configmap, need to restart istiod with the
# following command:
#     kubectl rollout restart deployment/istiod -n istio-system
#
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  name: istio
  namespace: istio-system
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
    extensionProviders:
    - name: "mlx-authz-http"
      envoyExtAuthzHttp:
        service: "mlx-ui.kubeflow.svc.cluster.local"
        port: "80"
        pathPrefix: "/session-validation"
        includeHeadersInCheck: ["cookie", "x-ext-authz"]
        headersToUpstreamOnAllow: ["kubeflow-userid"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
  meshNetworks: 'networks: {}'
