# Copyright 2021 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
kind: Kustomization
bases:
  - ../base
resources:
  - mlx-api-auth.yaml
  - mlx-ui-auth.yaml
  - mysql-auth.yaml
  - ml-pipeline-api-auth.yaml
  - mlx-ext-authz.yaml
  - istio-configmap.yaml
patchesStrategicMerge:
  - mlx-api-patch.yaml
