# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0

# Need to remove the "authn-filter" envoyfilter and replace it with
# this mlx-ext-authz
#
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mlx-ext-authz
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: "mlx-authz-http"
  rules:
  - to:
    - operation:
        notPaths: ["/mlx*"]
