# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mlx-api
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      service: mlx-api
  rules:
  # We need this rule to access the Swagger UI and post API requests directly to mlx-api
  - from:
    - source:
        namespaces:
        - istio-system
  - from:
    - source:
        principals:
        - cluster.local/ns/kubeflow/sa/mlx-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mlx-api
  namespace: kubeflow
spec:
  host: mlx-api.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlx-api-configmap
  namespace: kubeflow
data:
  # for kfp context.json
  # Note: currently these is only one user profile and mlx namespace.
  #       use the context which using 'mlx' namespace, to create kfp.KfpClient
  #       and send proper user headers to ml-pipeline api
  #       need to find a way to support multi user profile in the future
  kfp-context: |
    {
      "namespace": "mlx",
      "client_authentication_header_name": "kubeflow-userid",
      "client_authentication_header_value": "mlx@ibm.com"
    }
