# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
kind: Kustomization
bases:
  - ../base/mlx-deployments
resources:
  - minio.yaml
  - mysql.yaml
  - namespace.yaml
  - k8s-ingress.yaml
  - init-jobs.yaml
  - config.yaml
patchesStrategicMerge:
  - mlx-api-patch.yaml
  - mlx-ui-patch.yaml
configMapGenerator:
- name: mlx-parameters
  literals:
  # Update the credentials for the below fields before apply.
  - ingress-domain=ml-exchange.org
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: ingress-domain
  objref:
    kind: ConfigMap
    name: mlx-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ingress-domain
configurations:
- params.yaml
